name: flutter_starter
description: A minimal Flutter starter project for the bootcamp.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.18.0 <3.40.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.0.0
  dio: ^5.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  uses-material-design: true
