// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaAsVq6zVt3a2XndAhYk48rwOV5LG0r_Y',
    appId: '1:697286730105:web:4e0005cd91ee41bdb5cfa8',
    messagingSenderId: '697286730105',
    projectId: 'odc2025-54490',
    authDomain: 'odc2025-54490.firebaseapp.com',
    storageBucket: 'odc2025-54490.firebasestorage.app',
    measurementId: 'G-XYQP2LN272',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJIlyRMZo_ICPm5h-mSptN1W8c7jIZEUc',
    appId: '1:697286730105:android:f868f17d75d4687db5cfa8',
    messagingSenderId: '697286730105',
    projectId: 'odc2025-54490',
    storageBucket: 'odc2025-54490.firebasestorage.app',
  );
}
